/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.courtcasemgt;

/**
 *
 * @author PC
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLTITLE = new javax.swing.JLabel();
        LBLUSERNAME = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LBLPASSWORD = new javax.swing.JLabel();
        TXTUSERNAME = new javax.swing.JTextField();
        TXTPASSWORD = new javax.swing.JPasswordField();
        BTNLOGIN = new javax.swing.JButton();
        BTNEXIT = new javax.swing.JButton();
        BTNCLEAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBLTITLE.setText("COURT CASE MANAGEMENT");

        LBLUSERNAME.setText("USERNAME");

        LBLPASSWORD.setText("PASSWORD");

        BTNLOGIN.setText("LOGIN");
        BTNLOGIN.addActionListener(this::BTNLOGINActionPerformed);

        BTNEXIT.setText("EXIT");
        BTNEXIT.addActionListener(this::BTNEXITActionPerformed);

        BTNCLEAR.setText("CLEAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBLUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LBLPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXTUSERNAME, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(TXTPASSWORD)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(LBLTITLE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(BTNLOGIN)
                                .addGap(36, 36, 36)
                                .addComponent(BTNCLEAR)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(BTNEXIT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LBLTITLE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LBLUSERNAME)
                    .addComponent(TXTUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLPASSWORD)
                    .addComponent(TXTPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNLOGIN)
                    .addComponent(BTNCLEAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(BTNEXIT)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEXITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNEXITActionPerformed

    private void BTNLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLOGINActionPerformed
        // TODO add your handling code here:
         // Get the username entered by the user.
    String username = TXTUSERNAME.getText().trim();

    // Get the password entered by the user.
    String password = new String(TXTPASSWORD.getPassword());

    // Check whether the username field is empty.
    if (username.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please enter your username."
        );

        return;
    }

    // Check whether the password field is empty.
    if (password.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please enter your password."
        );

        return;
    }

    // SQL statement used to find the user in the database.
    String sql =
            "SELECT user_id, username, full_name, role "
            + "FROM users "
            + "WHERE username = ? AND password = ?";

    // Try to connect to the database.
    try (
        java.sql.Connection connection =
                DBConnection.getConnection();

        java.sql.PreparedStatement statement =
                connection.prepareStatement(sql)
    ) {

        // Put the username into the first ?.
        statement.setString(1, username);

        // Put the password into the second ?.
        statement.setString(2, password);

        // Execute the SQL query.
        java.sql.ResultSet result =
                statement.executeQuery();

        // Check whether a matching user was found.
        if (result.next()) {

            // Get information about the logged-in user.
            int userId = result.getInt("user_id");

            String fullName =
                    result.getString("full_name");

            String role =
                    result.getString("role");

            // Tell the user that login was successful.
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Login successful!\nWelcome, " + fullName
            );

            // Open the Main Menu.
            MainMenu menu =
                    new MainMenu(userId, fullName, role);

            menu.setVisible(true);

            // Close the Login window.
            this.dispose();

        } else {

            // No matching username/password was found.
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Invalid username or password."
            );
        }

    } catch (java.sql.SQLException e) {

        // Display the database error.
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Database error: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_BTNLOGINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCLEAR;
    private javax.swing.JButton BTNEXIT;
    private javax.swing.JButton BTNLOGIN;
    private javax.swing.JLabel LBLPASSWORD;
    private javax.swing.JLabel LBLTITLE;
    private javax.swing.JLabel LBLUSERNAME;
    private javax.swing.JPasswordField TXTPASSWORD;
    private javax.swing.JTextField TXTUSERNAME;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
